apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fiap-cloud-games
resources:
- k8s/00-namespace.yml
- k8s/01-configmap.yml
- k8s/10-rabbitmq.yml
- k8s/11-storage.yml
- k8s/20-users-api.yml
- k8s/21-catalog-api.yml
- k8s/22-payments-api.yml
- k8s/30-kong.yml
- k8s/40-monitoring.yml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: monitoring-config
  files:
  - monitoring/prometheus.yml
  - monitoring/loki.yml
  - monitoring/datasources.yml
  - monitoring/dashboards.yml
  - monitoring/fcg-dashboard.json
  - monitoring/kubernetes.alloy
secretGenerator:
- name: fcg-secrets
  envs:
  - .local/app.env
- name: kong-config
  files:
  - .local/kong.yml
- name: rabbit-config
  files:
  - rabbitmq/rabbitmq.conf
  - .local/definitions.json
