{
 "title": "FCG - Fase 3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisicoes por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_received_total[1m]))",
     "legendFormat": "{{job}} {{code}} {{result}}"
    }
   ]
  },
  {
   "title": "Latencia p95",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "{{job}} {{code}} {{result}}"
    }
   ]
  },
  {
   "title": "Requisicoes totais por status HTTP",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, code) (http_requests_received_total)",
     "legendFormat": "{{job}} {{code}} {{result}}"
    }
   ]
  },
  {
   "title": "Taxa de erros 5xx (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by (job) (rate(http_requests_received_total{code=~\"5..\"}[1m])) or on(job) (0 * sum by (job) (rate(http_requests_received_total[1m])))) / clamp_min(sum by (job) (rate(http_requests_received_total[1m])), 0.001)",
     "legendFormat": "{{job}} {{code}} {{result}}"
    }
   ]
  },
  {
   "title": "Cache de avaliacoes: HIT / MISS / BYPASS",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (result) (fcg_review_cache_total)",
     "legendFormat": "{{job}} {{code}} {{result}}"
    }
   ]
  },
  {
   "title": "Servicos monitorados (1 = disponivel)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=~\"users-api|catalog-api|payments-api\"}",
     "legendFormat": "{{job}} {{code}} {{result}}"
    }
   ]
  },
  {
   "title": "Logs centralizados das notificacoes",
   "type": "logs",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{service=\"notifications-function\"}"
    }
   ]
  }
 ]
}