apiVersion: v1
kind: Secret
metadata:
  name: fiap-cloud-games-secret
  namespace: fiap-cloud-games
type: Opaque
stringData:
  Jwt__Key: FIAP-TechChallenge-chave-local-dev-com-pelo-menos-32-caracteres
