apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: rabbit-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: rabbitmq
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: rabbitmq
    template:
      metadata:
        labels:
          app: rabbitmq
      spec:
        hostname: rabbitmq
        containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5672
          - containerPort: 15672
          env: []
          envFrom:
          - configMapRef:
              name: fcg-config
          - secretRef:
              name: fcg-secrets
          volumeMounts:
          - name: data
            mountPath: /var/lib/rabbitmq
          - name: rabbit-config
            mountPath: /etc/rabbitmq/rabbitmq.conf
            subPath: rabbitmq.conf
          - name: rabbit-config
            mountPath: /etc/rabbitmq/definitions.json
            subPath: definitions.json
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbit-data
        - name: rabbit-config
          secret:
            secretName: rabbit-config
- apiVersion: v1
  kind: Service
  metadata:
    name: rabbitmq
    namespace: fiap-cloud-games
  spec:
    selector:
      app: rabbitmq
    ports:
    - name: port-0
      port: 5672
      targetPort: 5672
      nodePort: 30672
    - name: port-1
      port: 15672
      targetPort: 15672
      nodePort: 31672
    type: NodePort
