apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mongo-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mongo
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: mongo
    template:
      metadata:
        labels:
          app: mongo
      spec:
        containers:
        - name: mongo
          image: mongo:7.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27017
          env: []
          envFrom: []
          volumeMounts:
          - name: data
            mountPath: /data/db
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data
- apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    namespace: fiap-cloud-games
  spec:
    selector:
      app: mongo
    ports:
    - name: port-0
      port: 27017
      targetPort: 27017
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: redis
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: redis
    template:
      metadata:
        labels:
          app: redis
      spec:
        containers:
        - name: redis
          image: redis:7.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 6379
          args:
          - --maxmemory
          - 128mb
          - --maxmemory-policy
          - allkeys-lru
          env: []
          envFrom: []
          volumeMounts: []
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes: []
- apiVersion: v1
  kind: Service
  metadata:
    name: redis
    namespace: fiap-cloud-games
  spec:
    selector:
      app: redis
    ports:
    - name: port-0
      port: 6379
      targetPort: 6379
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: azurite-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: azurite
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: azurite
    template:
      metadata:
        labels:
          app: azurite
      spec:
        containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:3.35.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10000
          - containerPort: 10001
          - containerPort: 10002
          args:
          - azurite
          - --blobHost
          - 0.0.0.0
          - --queueHost
          - 0.0.0.0
          - --tableHost
          - 0.0.0.0
          - --skipApiVersionCheck
          - --disableProductStyleUrl
          env: []
          envFrom:
          - configMapRef:
              name: fcg-config
          - secretRef:
              name: fcg-secrets
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: azurite-data
- apiVersion: v1
  kind: Service
  metadata:
    name: azurite
    namespace: fiap-cloud-games
  spec:
    selector:
      app: azurite
    ports:
    - name: port-0
      port: 10000
      targetPort: 10000
    - name: port-1
      port: 10001
      targetPort: 10001
    - name: port-2
      port: 10002
      targetPort: 10002
    type: ClusterIP
