apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: catalog-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: catalog-api
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: catalog-api
    template:
      metadata:
        labels:
          app: catalog-api
      spec:
        containers:
        - name: catalog-api
          image: fiap-catalog-api:fase3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: ConnectionStrings__Db
            value: Data Source=/app/data/catalog.db
          envFrom:
          - configMapRef:
              name: fcg-config
          - secretRef:
              name: fcg-secrets
          volumeMounts:
          - name: data
            mountPath: /app/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: catalog-data
- apiVersion: v1
  kind: Service
  metadata:
    name: catalog-api
    namespace: fiap-cloud-games
  spec:
    selector:
      app: catalog-api
    ports:
    - name: port-0
      port: 8080
      targetPort: 8080
    type: ClusterIP
