apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: payments-api
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: payments-api
    template:
      metadata:
        labels:
          app: payments-api
      spec:
        containers:
        - name: payments-api
          image: fiap-payments-api:fase3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env: []
          envFrom:
          - configMapRef:
              name: fcg-config
          - secretRef:
              name: fcg-secrets
          volumeMounts: []
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
        volumes: []
- apiVersion: v1
  kind: Service
  metadata:
    name: payments-api
    namespace: fiap-cloud-games
  spec:
    selector:
      app: payments-api
    ports:
    - name: port-0
      port: 8080
      targetPort: 8080
    type: ClusterIP
