apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kong
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: kong
    template:
      metadata:
        labels:
          app: kong
      spec:
        containers:
        - name: kong
          image: kong:3.9
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
          env:
          - name: KONG_NGINX_WORKER_PROCESSES
            value: '2'
          - name: KONG_DATABASE
            value: 'off'
          - name: KONG_DECLARATIVE_CONFIG
            value: /etc/kong/kong.yml
          - name: KONG_ADMIN_LISTEN
            value: 'off'
          envFrom: []
          volumeMounts:
          - name: kong-config
            mountPath: /etc/kong
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: kong-config
          secret:
            secretName: kong-config
- apiVersion: v1
  kind: Service
  metadata:
    name: kong
    namespace: fiap-cloud-games
  spec:
    selector:
      app: kong
    ports:
    - name: port-0
      port: 8000
      targetPort: 8000
      nodePort: 30080
    type: NodePort
