apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: prometheus-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: prometheus
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: prometheus
    template:
      metadata:
        labels:
          app: prometheus
      spec:
        containers:
        - name: prometheus
          image: prom/prometheus:v3.2.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9090
          args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus
          - --storage.tsdb.retention.time=7d
          env: []
          envFrom: []
          volumeMounts:
          - name: data
            mountPath: /prometheus
          - name: config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data
        - name: config
          configMap:
            name: monitoring-config
        securityContext:
          fsGroup: 65534
- apiVersion: v1
  kind: Service
  metadata:
    name: prometheus
    namespace: fiap-cloud-games
  spec:
    selector:
      app: prometheus
    ports:
    - name: port-0
      port: 9090
      targetPort: 9090
      nodePort: 30090
    type: NodePort
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: loki-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: loki
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: loki
    template:
      metadata:
        labels:
          app: loki
      spec:
        containers:
        - name: loki
          image: grafana/loki:3.4.2
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3100
          args:
          - -config.file=/etc/loki/loki.yml
          env: []
          envFrom: []
          volumeMounts:
          - name: data
            mountPath: /loki
          - name: config
            mountPath: /etc/loki/loki.yml
            subPath: loki.yml
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: loki-data
        - name: config
          configMap:
            name: monitoring-config
        securityContext:
          fsGroup: 10001
- apiVersion: v1
  kind: Service
  metadata:
    name: loki
    namespace: fiap-cloud-games
  spec:
    selector:
      app: loki
    ports:
    - name: port-0
      port: 3100
      targetPort: 3100
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-data
    namespace: fiap-cloud-games
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: grafana
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: grafana
    template:
      metadata:
        labels:
          app: grafana
      spec:
        containers:
        - name: grafana
          image: grafana/grafana:11.6.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_USERS_ALLOW_SIGN_UP
            value: 'false'
          envFrom:
          - configMapRef:
              name: fcg-config
          - secretRef:
              name: fcg-secrets
          volumeMounts:
          - name: data
            mountPath: /var/lib/grafana
          - name: config
            subPath: datasources.yml
            mountPath: /etc/grafana/provisioning/datasources/fcg.yml
          - name: config
            subPath: dashboards.yml
            mountPath: /etc/grafana/provisioning/dashboards/fcg.yml
          - name: config
            subPath: fcg-dashboard.json
            mountPath: /var/lib/grafana/dashboards/fcg.json
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-data
        - name: config
          configMap:
            name: monitoring-config
        securityContext:
          fsGroup: 472
- apiVersion: v1
  kind: Service
  metadata:
    name: grafana
    namespace: fiap-cloud-games
  spec:
    selector:
      app: grafana
    ports:
    - name: port-0
      port: 3000
      targetPort: 3000
      nodePort: 30300
    type: NodePort
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: alloy
    namespace: fiap-cloud-games
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: alloy
    namespace: fiap-cloud-games
  rules:
  - apiGroups:
    - ''
    resources:
    - pods
    - pods/log
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: alloy
    namespace: fiap-cloud-games
  subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: fiap-cloud-games
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: alloy
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: alloy
    namespace: fiap-cloud-games
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: alloy
    template:
      metadata:
        labels:
          app: alloy
      spec:
        serviceAccountName: alloy
        containers:
        - name: alloy
          image: grafana/alloy:v1.8.3
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 12345
          args:
          - run
          - /etc/alloy/config.alloy
          - --storage.path=/var/lib/alloy
          env: []
          envFrom: []
          volumeMounts:
          - name: config
            mountPath: /etc/alloy/config.alloy
            subPath: kubernetes.alloy
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 768Mi
        volumes:
        - name: config
          configMap:
            name: monitoring-config
